"""Criação inicial das tabelas

Revision ID: 661961ac8a39
Revises: 
Create Date: 2025-05-27 22:14:09.630718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661961ac8a39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
